// @generated by substreams protogen (manually maintained)
// source: proto/polaris.proto
// package: polaris.v1
//
// To regenerate: substreams protogen ./substreams.yaml --exclude-paths="sf/substreams,google"

pub mod v1 {
    /// Events extracted from the Polaris Music Registry contract
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct Events {
        #[prost(message, repeated, tag = "1")]
        pub events: ::prost::alloc::vec::Vec<Event>,
    }

    /// Individual event from the blockchain
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct Event {
        /// Transaction hash
        #[prost(string, tag = "1")]
        pub tx_hash: ::prost::alloc::string::String,
        /// Block number
        #[prost(uint64, tag = "2")]
        pub block_num: u64,
        /// Block timestamp
        #[prost(uint64, tag = "3")]
        pub timestamp: u64,
        /// Event type (PUT, ATTEST, VOTE, etc.)
        #[prost(string, tag = "4")]
        pub event_type: ::prost::alloc::string::String,
        /// Event-specific data
        #[prost(message, optional, tag = "5")]
        pub data: ::core::option::Option<EventData>,
    }

    /// Event data union
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct EventData {
        #[prost(oneof = "event_data::Event", tags = "1, 2, 3, 4, 5, 6, 7, 8, 9")]
        pub event: ::core::option::Option<event_data::Event>,
    }

    /// Nested message and enum types in `EventData`.
    pub mod event_data {
        #[allow(clippy::derive_partial_eq_without_eq)]
        #[derive(Clone, PartialEq, ::prost::Oneof)]
        pub enum Event {
            #[prost(message, tag = "1")]
            Put(super::PutEvent),
            #[prost(message, tag = "2")]
            Attest(super::AttestEvent),
            #[prost(message, tag = "3")]
            Vote(super::VoteEvent),
            #[prost(message, tag = "4")]
            Finalize(super::FinalizeEvent),
            #[prost(message, tag = "5")]
            Stake(super::StakeEvent),
            #[prost(message, tag = "6")]
            Unstake(super::UnstakeEvent),
            #[prost(message, tag = "7")]
            Like(super::LikeEvent),
            #[prost(message, tag = "8")]
            Unlike(super::UnlikeEvent),
            #[prost(message, tag = "9")]
            Updrespect(super::UpdateRespectEvent),
        }
    }

    /// Put action data
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct PutEvent {
        #[prost(string, tag = "1")]
        pub author: ::prost::alloc::string::String,
        #[prost(uint32, tag = "2")]
        pub type_: u32,
        /// SHA256 hash as hex string
        #[prost(string, tag = "3")]
        pub hash: ::prost::alloc::string::String,
        /// Optional parent hash
        #[prost(string, tag = "4")]
        pub parent: ::prost::alloc::string::String,
        #[prost(uint64, tag = "5")]
        pub ts: u64,
        #[prost(string, repeated, tag = "6")]
        pub tags: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
        #[prost(uint64, tag = "7")]
        pub expires_at: u64,
    }

    /// Attest action data
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct AttestEvent {
        #[prost(string, tag = "1")]
        pub attestor: ::prost::alloc::string::String,
        #[prost(string, tag = "2")]
        pub tx_hash: ::prost::alloc::string::String,
        #[prost(uint32, tag = "3")]
        pub confirmed_type: u32,
    }

    /// Vote action data
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct VoteEvent {
        #[prost(string, tag = "1")]
        pub voter: ::prost::alloc::string::String,
        #[prost(string, tag = "2")]
        pub tx_hash: ::prost::alloc::string::String,
        /// +1, 0, -1
        #[prost(int32, tag = "3")]
        pub val: i32,
        /// Respect weight
        #[prost(uint32, tag = "4")]
        pub weight: u32,
    }

    /// Finalize action data
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct FinalizeEvent {
        #[prost(string, tag = "1")]
        pub tx_hash: ::prost::alloc::string::String,
        #[prost(bool, tag = "2")]
        pub accepted: bool,
        /// 0-100
        #[prost(uint64, tag = "3")]
        pub approval_percent: u64,
        #[prost(uint64, tag = "4")]
        pub reward_amount: u64,
    }

    /// Stake action data
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct StakeEvent {
        #[prost(string, tag = "1")]
        pub account: ::prost::alloc::string::String,
        #[prost(string, tag = "2")]
        pub node_id: ::prost::alloc::string::String,
        /// Asset string (e.g., "100.0000 MUS")
        #[prost(string, tag = "3")]
        pub quantity: ::prost::alloc::string::String,
    }

    /// Unstake action data
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct UnstakeEvent {
        #[prost(string, tag = "1")]
        pub account: ::prost::alloc::string::String,
        #[prost(string, tag = "2")]
        pub node_id: ::prost::alloc::string::String,
        #[prost(string, tag = "3")]
        pub quantity: ::prost::alloc::string::String,
    }

    /// Like action data
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct LikeEvent {
        #[prost(string, tag = "1")]
        pub account: ::prost::alloc::string::String,
        #[prost(string, tag = "2")]
        pub node_id: ::prost::alloc::string::String,
        /// Path of node IDs
        #[prost(string, repeated, tag = "3")]
        pub path: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    }

    /// Unlike action data
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct UnlikeEvent {
        #[prost(string, tag = "1")]
        pub account: ::prost::alloc::string::String,
        #[prost(string, tag = "2")]
        pub node_id: ::prost::alloc::string::String,
    }

    /// Update Respect action data
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct UpdateRespectEvent {
        #[prost(message, repeated, tag = "1")]
        pub updates: ::prost::alloc::vec::Vec<RespectUpdate>,
        #[prost(uint64, tag = "2")]
        pub election_round: u64,
    }

    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct RespectUpdate {
        #[prost(string, tag = "1")]
        pub account: ::prost::alloc::string::String,
        #[prost(uint32, tag = "2")]
        pub respect: u32,
    }

    /// Statistics aggregated from events
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct Stats {
        #[prost(uint64, tag = "1")]
        pub total_events: u64,
        #[prost(uint64, tag = "2")]
        pub total_puts: u64,
        #[prost(uint64, tag = "3")]
        pub total_votes: u64,
        #[prost(uint64, tag = "4")]
        pub total_stakes: u64,
        #[prost(uint64, tag = "5")]
        pub total_likes: u64,
        #[prost(uint64, tag = "6")]
        pub unique_contributors: u64,
        #[prost(string, tag = "7")]
        pub total_staked_amount: ::prost::alloc::string::String,
    }

    /// Account activity tracking
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct AccountActivity {
        #[prost(string, tag = "1")]
        pub account: ::prost::alloc::string::String,
        #[prost(uint64, tag = "2")]
        pub events_submitted: u64,
        #[prost(uint64, tag = "3")]
        pub votes_cast: u64,
        #[prost(uint64, tag = "4")]
        pub stakes_made: u64,
        #[prost(uint64, tag = "5")]
        pub likes_given: u64,
        #[prost(uint64, tag = "6")]
        pub last_active_block: u64,
    }

    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct AccountActivities {
        #[prost(message, repeated, tag = "1")]
        pub activities: ::prost::alloc::vec::Vec<AccountActivity>,
    }

    /// AnchoredEvent: Event with complete blockchain provenance
    /// This is the primary output for chain ingestion (T5)
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct AnchoredEvent {
        /// Canonical content hash from put.hash (SHA256 of off-chain event JSON)
        #[prost(string, tag = "1")]
        pub content_hash: ::prost::alloc::string::String,
        /// SHA256 hash of action payload (for debugging/trace identity)
        #[prost(string, tag = "2")]
        pub event_hash: ::prost::alloc::string::String,
        /// Raw action JSON payload (contains put.hash)
        #[prost(bytes = "vec", tag = "3")]
        pub payload: ::prost::alloc::vec::Vec<u8>,
        /// Block number
        #[prost(uint64, tag = "4")]
        pub block_num: u64,
        /// Block ID (hex)
        #[prost(string, tag = "5")]
        pub block_id: ::prost::alloc::string::String,
        /// Transaction ID (hex)
        #[prost(string, tag = "6")]
        pub trx_id: ::prost::alloc::string::String,
        /// Action index within transaction
        #[prost(uint32, tag = "7")]
        pub action_ordinal: u32,
        /// Block timestamp (Unix seconds)
        #[prost(uint64, tag = "8")]
        pub timestamp: u64,
        /// Source identifier (e.g., "substreams-eos")
        #[prost(string, tag = "9")]
        pub source: ::prost::alloc::string::String,
        /// Contract account name
        #[prost(string, tag = "10")]
        pub contract_account: ::prost::alloc::string::String,
        /// Action name (e.g., "put")
        #[prost(string, tag = "11")]
        pub action_name: ::prost::alloc::string::String,
    }

    /// Collection of anchored events
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct AnchoredEvents {
        #[prost(message, repeated, tag = "1")]
        pub events: ::prost::alloc::vec::Vec<AnchoredEvent>,
    }
}
